# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/aiying/Nova

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/aiying/Nova/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/aiying/Nova/build/CMakeFiles /data/aiying/Nova/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/aiying/Nova/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _nova_geometry

# Build rule for target.
_nova_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _nova_geometry
.PHONY : _nova_geometry

# fast build rule for target.
_nova_geometry/fast:
	$(MAKE) -f Library/Geometry/CMakeFiles/_nova_geometry.dir/build.make Library/Geometry/CMakeFiles/_nova_geometry.dir/build
.PHONY : _nova_geometry/fast

#=============================================================================
# Target rules for targets named _nova_spgrid

# Build rule for target.
_nova_spgrid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _nova_spgrid
.PHONY : _nova_spgrid

# fast build rule for target.
_nova_spgrid/fast:
	$(MAKE) -f Library/SPGrid/CMakeFiles/_nova_spgrid.dir/build.make Library/SPGrid/CMakeFiles/_nova_spgrid.dir/build
.PHONY : _nova_spgrid/fast

#=============================================================================
# Target rules for targets named _nova_tools

# Build rule for target.
_nova_tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _nova_tools
.PHONY : _nova_tools

# fast build rule for target.
_nova_tools/fast:
	$(MAKE) -f Library/Tools/CMakeFiles/_nova_tools.dir/build.make Library/Tools/CMakeFiles/_nova_tools.dir/build
.PHONY : _nova_tools/fast

#=============================================================================
# Target rules for targets named ClassGridUnitTest

# Build rule for target.
ClassGridUnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClassGridUnitTest
.PHONY : ClassGridUnitTest

# fast build rule for target.
ClassGridUnitTest/fast:
	$(MAKE) -f Tests/Tools/CMakeFiles/ClassGridUnitTest.dir/build.make Tests/Tools/CMakeFiles/ClassGridUnitTest.dir/build
.PHONY : ClassGridUnitTest/fast

#=============================================================================
# Target rules for targets named opengl_kernel

# Build rule for target.
opengl_kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opengl_kernel
.PHONY : opengl_kernel

# fast build rule for target.
opengl_kernel/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/CMakeFiles/opengl_kernel.dir/build.make Projects/Nova_Examples/opengl/CMakeFiles/opengl_kernel.dir/build
.PHONY : opengl_kernel/fast

#=============================================================================
# Target rules for targets named opengl

# Build rule for target.
opengl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opengl
.PHONY : opengl

# fast build rule for target.
opengl/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/CMakeFiles/opengl.dir/build.make Projects/Nova_Examples/opengl/CMakeFiles/opengl.dir/build
.PHONY : opengl/fast

#=============================================================================
# Target rules for targets named plugin_Assimp

# Build rule for target.
plugin_Assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_Assimp
.PHONY : plugin_Assimp

# fast build rule for target.
plugin_Assimp/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/plugins/Assimp/CMakeFiles/plugin_Assimp.dir/build.make Projects/Nova_Examples/opengl/plugins/Assimp/CMakeFiles/plugin_Assimp.dir/build
.PHONY : plugin_Assimp/fast

#=============================================================================
# Target rules for targets named plugin_Assimp_miniball

# Build rule for target.
plugin_Assimp_miniball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_Assimp_miniball
.PHONY : plugin_Assimp_miniball

# fast build rule for target.
plugin_Assimp_miniball/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/plugins/Assimp/miniball/CMakeFiles/plugin_Assimp_miniball.dir/build.make Projects/Nova_Examples/opengl/plugins/Assimp/miniball/CMakeFiles/plugin_Assimp_miniball.dir/build
.PHONY : plugin_Assimp_miniball/fast

#=============================================================================
# Target rules for targets named plugin_Grid

# Build rule for target.
plugin_Grid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_Grid
.PHONY : plugin_Grid

# fast build rule for target.
plugin_Grid/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/plugins/Grid/CMakeFiles/plugin_Grid.dir/build.make Projects/Nova_Examples/opengl/plugins/Grid/CMakeFiles/plugin_Grid.dir/build
.PHONY : plugin_Grid/fast

#=============================================================================
# Target rules for targets named plugin_FreeTypeRenderer

# Build rule for target.
plugin_FreeTypeRenderer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_FreeTypeRenderer
.PHONY : plugin_FreeTypeRenderer

# fast build rule for target.
plugin_FreeTypeRenderer/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/plugins/FreeTypeTextRenderer/CMakeFiles/plugin_FreeTypeRenderer.dir/build.make Projects/Nova_Examples/opengl/plugins/FreeTypeTextRenderer/CMakeFiles/plugin_FreeTypeRenderer.dir/build
.PHONY : plugin_FreeTypeRenderer/fast

#=============================================================================
# Target rules for targets named plugin_TextFileRenderer

# Build rule for target.
plugin_TextFileRenderer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_TextFileRenderer
.PHONY : plugin_TextFileRenderer

# fast build rule for target.
plugin_TextFileRenderer/fast:
	$(MAKE) -f Projects/Nova_Examples/opengl/plugins/TextFileRenderer/CMakeFiles/plugin_TextFileRenderer.dir/build.make Projects/Nova_Examples/opengl/plugins/TextFileRenderer/CMakeFiles/plugin_TextFileRenderer.dir/build
.PHONY : plugin_TextFileRenderer/fast

#=============================================================================
# Target rules for targets named embedded_deformables_2d

# Build rule for target.
embedded_deformables_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embedded_deformables_2d
.PHONY : embedded_deformables_2d

# fast build rule for target.
embedded_deformables_2d/fast:
	$(MAKE) -f Projects/Nova_Examples/embedded_deformables/embedded_deformables_2d/CMakeFiles/embedded_deformables_2d.dir/build.make Projects/Nova_Examples/embedded_deformables/embedded_deformables_2d/CMakeFiles/embedded_deformables_2d.dir/build
.PHONY : embedded_deformables_2d/fast

#=============================================================================
# Target rules for targets named embedded_deformables_3d

# Build rule for target.
embedded_deformables_3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embedded_deformables_3d
.PHONY : embedded_deformables_3d

# fast build rule for target.
embedded_deformables_3d/fast:
	$(MAKE) -f Projects/Nova_Examples/embedded_deformables/embedded_deformables_3d/CMakeFiles/embedded_deformables_3d.dir/build.make Projects/Nova_Examples/embedded_deformables/embedded_deformables_3d/CMakeFiles/embedded_deformables_3d.dir/build
.PHONY : embedded_deformables_3d/fast

#=============================================================================
# Target rules for targets named plugin_Embedded_Deformables

# Build rule for target.
plugin_Embedded_Deformables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_Embedded_Deformables
.PHONY : plugin_Embedded_Deformables

# fast build rule for target.
plugin_Embedded_Deformables/fast:
	$(MAKE) -f Projects/Nova_Examples/embedded_deformables/plugin_Embedded_Deformables/CMakeFiles/plugin_Embedded_Deformables.dir/build.make Projects/Nova_Examples/embedded_deformables/plugin_Embedded_Deformables/CMakeFiles/plugin_Embedded_Deformables.dir/build
.PHONY : plugin_Embedded_Deformables/fast

#=============================================================================
# Target rules for targets named astrocytes_2d

# Build rule for target.
astrocytes_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 astrocytes_2d
.PHONY : astrocytes_2d

# fast build rule for target.
astrocytes_2d/fast:
	$(MAKE) -f Projects/Adaptive_Poisson_Systems/astrocytes_2d/CMakeFiles/astrocytes_2d.dir/build.make Projects/Adaptive_Poisson_Systems/astrocytes_2d/CMakeFiles/astrocytes_2d.dir/build
.PHONY : astrocytes_2d/fast

#=============================================================================
# Target rules for targets named explicit_astrocytes_2d

# Build rule for target.
explicit_astrocytes_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 explicit_astrocytes_2d
.PHONY : explicit_astrocytes_2d

# fast build rule for target.
explicit_astrocytes_2d/fast:
	$(MAKE) -f Projects/Adaptive_Poisson_Systems/explicit_astrocytes_2d/CMakeFiles/explicit_astrocytes_2d.dir/build.make Projects/Adaptive_Poisson_Systems/explicit_astrocytes_2d/CMakeFiles/explicit_astrocytes_2d.dir/build
.PHONY : explicit_astrocytes_2d/fast

#=============================================================================
# Target rules for targets named poisson_2d

# Build rule for target.
poisson_2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poisson_2d
.PHONY : poisson_2d

# fast build rule for target.
poisson_2d/fast:
	$(MAKE) -f Projects/Adaptive_Poisson_Systems/poisson_2d/CMakeFiles/poisson_2d.dir/build.make Projects/Adaptive_Poisson_Systems/poisson_2d/CMakeFiles/poisson_2d.dir/build
.PHONY : poisson_2d/fast

#=============================================================================
# Target rules for targets named point_process

# Build rule for target.
point_process: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 point_process
.PHONY : point_process

# fast build rule for target.
point_process/fast:
	$(MAKE) -f Projects/Adaptive_Poisson_Systems/point_process/CMakeFiles/point_process.dir/build.make Projects/Adaptive_Poisson_Systems/point_process/CMakeFiles/point_process.dir/build
.PHONY : point_process/fast

#=============================================================================
# Target rules for targets named plugin_Adaptive_Poisson_Systems

# Build rule for target.
plugin_Adaptive_Poisson_Systems: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_Adaptive_Poisson_Systems
.PHONY : plugin_Adaptive_Poisson_Systems

# fast build rule for target.
plugin_Adaptive_Poisson_Systems/fast:
	$(MAKE) -f Projects/Adaptive_Poisson_Systems/plugin_Adaptive_Poisson_Systems/CMakeFiles/plugin_Adaptive_Poisson_Systems.dir/build.make Projects/Adaptive_Poisson_Systems/plugin_Adaptive_Poisson_Systems/CMakeFiles/plugin_Adaptive_Poisson_Systems.dir/build
.PHONY : plugin_Adaptive_Poisson_Systems/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... _nova_geometry"
	@echo "... _nova_spgrid"
	@echo "... _nova_tools"
	@echo "... ClassGridUnitTest"
	@echo "... opengl_kernel"
	@echo "... opengl"
	@echo "... plugin_Assimp"
	@echo "... plugin_Assimp_miniball"
	@echo "... plugin_Grid"
	@echo "... plugin_FreeTypeRenderer"
	@echo "... plugin_TextFileRenderer"
	@echo "... embedded_deformables_2d"
	@echo "... embedded_deformables_3d"
	@echo "... plugin_Embedded_Deformables"
	@echo "... astrocytes_2d"
	@echo "... explicit_astrocytes_2d"
	@echo "... poisson_2d"
	@echo "... point_process"
	@echo "... plugin_Adaptive_Poisson_Systems"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

